### ISSUE TITLE
Error 401 - Converting %2C to , in image url

### ISSUE THREAD

**Issue by Nav33d** [aelvan/Imager-Craft#66]
Hi,

I'm passing an external url to imager and it is converting %2C to , which results in 401 error.

Original URL:
```
https://i.guim.co.uk/img/media/de57cb899cdbe150331acb2de4fa816aca20b12e/0_155_4992_2995/master/4992.jpg?w=1200&h=630&q=55&auto=format&usm=12&fit=crop&crop=faces%2Centropy&bm=normal&ba=bottom%2Cleft&blend64=aHR0cHM6Ly91cGxvYWRzLmd1aW0uY28udWsvMjAxNi8wNS8yNS9vdmVybGF5LWxvZ28tMTIwMC05MF9vcHQucG5n&s=bb524716e8e010911d74da0ddf1ebfcc
```

Imager URL:
```
https://i.guim.co.uk/img/media/de57cb899cdbe150331acb2de4fa816aca20b12e/0_155_4992_2995/master/4992.jpg?w=1200&h=630&q=55&auto=format&usm=12&fit=crop&crop=faces,entropy&bm=normal&ba=bottom,left&blend64=aHR0cHM6Ly91cGxvYWRzLmd1aW0uY28udWsvMjAxNi8wNS8yNS9vdmVybGF5LWxvZ28tMTIwMC05MF9vcHQucG5n&s=bb524716e8e010911d74da0ddf1ebfcc
```

Could you please advise if there is a way to avoid this conversion?

Many thanks

**Comment by aelvan** [comment]
Seems to be an issue where query strings were urldecoded. Think I've fixed it, could you try to replace the `Imager_ImagePathsModel.php` file in the `imager/models` folder with the attached, zipped one, and report back if that fixes your issue (and doesn't introduce any new ones ;))?

[Imager_ImagePathsModel.php.zip](https://github.com/aelvan/Imager-Craft/files/692265/Imager_ImagePathsModel.php.zip)

**Comment by aelvan** [comment]
Hi @Nav33d did you get a chance to test this fix?

**Comment by Nav33d** [comment]
Hi @aelvan, Apologies for the delayed reply! I'm still getting the same error :(
